name: flutter_aplication_2
description: "A new Flutter project."

publish_to: 'none' # 

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.12
  sqflite: ^2.0.0+4
  path_provider: ^2.0.8
  intl: ^0.20.1
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_rating_bar: ^4.0.0
  
dependency_overrides:
  characters: ^1.3.1
  collection: ^1.19.1
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  async: ^2.12.0
  boolean_selector: ^2.1.2
  clock: ^1.1.2
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  lints: ^5.1.0
  matcher: ^0.12.17
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.3
  vm_service: ^15.0.0
  source_span: ^1.10.1
  stream_channel: 2.1.4
  term_glyph: ^1.2.2
  shared_preferences: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - imagens/background.png
